version: 2.1

jobs:
  node:
    docker:
      - image: cimg/node:21.6.1
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-deps-{{ checksum "package-lock.json" }}
            - node-deps-
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          paths:
            - ~/.npm
          key: node-deps-{{ checksum "package-lock.json" }}
      - run:
          name: Run eslint
          command: npm run lint
      - run:
          name: Run test
          command: npm test -- --ci --coverage

  python:
    docker:
      - image: cimg/python:3.13.1-browsers
    steps:
      - checkout
      - restore_cache:
          keys:
            - python-deps-{{ checksum "tests/requirements.txt" }}
            - python-deps-
      - run:
          name: Install dependencies
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r tests/requirements.txt
      - save_cache:
          paths:
            - ~/.cache/pip
          key: python-deps-{{ checksum "tests/requirements.txt" }}
      - run:
          name: Show installed Python packages
          command: |
            . venv/bin/activate
            pip list -v
      - run:
          name: Run flake8
          command: |
            . venv/bin/activate
            flake8 .
      - run:
          name: Run black
          command: |
            . venv/bin/activate
            black --check . dash_chat
      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            pytest tests/

workflows:
  version: 2
  build-and-test:
    jobs:
      - node
      - python
