version: 2.1

orbs:
  win: circleci/windows@5.0.0

jobs:
  node:
    docker:
      - image: cimg/node:21.6.1
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Run eslint
          command: npm run lint
      - run:
          name: Run test
          command: npm test -- --ci --coverage

  python:
    docker:
      - image: circleci/python:3.9
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install -r tests/requirements.txt
      - run:
          name: Run flake8
          command: |
            . venv/bin/activate
            flake8 .
      - run:
          name: Run black
          command: |
            . venv/bin/activate
            black --check tests usage.py
      - run:
          name: Run tests
          command: pytest tests/

workflows:
  version: 2
  build-and-test:
    jobs:
      - node
      - python
